# Generated by Django 5.0.3 on 2024-05-13 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_games', models.IntegerField()),
                ('total_wins', models.IntegerField()),
                ('total_losses', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('profile_picture', models.ImageField(default='profile-pictures/default.svg', upload_to='profile-pictures/')),
                ('is_online', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, default=None, null=True)),
                ('mmr', models.IntegerField(default=1000)),
                ('blocked_users', models.ManyToManyField(blank=True, related_name='users_blocked', to='Profile.profile')),
                ('friends', models.ManyToManyField(blank=True, related_name='profile_friends', to='Profile.profile')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stats', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.stats')),
            ],
        ),
    ]
