# Generated by Django 5.0.3 on 2024-05-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_42auth',
            field=models.BooleanField(default=False),
        ),
    ]
