# Generated by Django 5.0.3 on 2024-05-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_color',
            field=models.CharField(choices=[('white', 'White'), ('blue', 'Blue'), ('red', 'Red'), ('green', 'Green')], default='white', max_length=7),
        ),
    ]
