# Generated by Django 5.0.3 on 2024-03-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
