# Generated by Django 5.0.3 on 2024-03-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profile_is_verified_alter_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
