# Generated by Django 5.0.3 on 2024-05-20 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Profile', '0002_profile_preferred_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=100, unique=True,
                                   validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
