# Generated by Django 5.0.3 on 2024-05-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_color',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile-pictures/default.png', upload_to='profile-pictures/'),
        ),
    ]
