# Generated by Django 5.0.3 on 2024-03-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
