# Generated by Django 5.0.3 on 2024-03-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profile_is_verified_alter_profile_nickname'),
        ('Profile', '0010_profile_user'),
    ]

    operations = [
    ]
