# Generated by Django 5.0.3 on 2024-03-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_profile_bio'),
        ('Profile', '0011_merge_20240318_1849'),
    ]

    operations = [
    ]
