# Generated by Django 5.0.3 on 2024-03-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0014_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile-pictures/default.svg', null=True, upload_to='profile-pictures/'),
        ),
    ]
