# Generated by Django 5.0.3 on 2024-04-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0018_alter_profile_nickname'),
        ('Profile', '0019_stats_points'),
    ]

    operations = [
    ]
