# Generated by Django 5.0.3 on 2024-04-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0020_merge_0018_alter_profile_nickname_0019_stats_points'),
        ('Profile', '0020_profile_blocked_users_alter_profile_friends'),
    ]

    operations = [
    ]
