# Generated by Django 5.0.3 on 2024-04-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0020_profile_mmr'),
        ('Profile', '0021_merge_20240416_1943'),
    ]

    operations = [
    ]
