version: '3.8'

services:
  postgres:
    build:
      context: psql
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./psql/data:/var/lib/postgresql/data
    networks:
      - deploy

  backend:
    build:
      context: API
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=API.settings
      - DATABASE_URL=postgres://postgres:123@postgres:5432/transcendenceDB
    volumes:
      - ./Nginx/nginx.crt:/API/nginx.crt
      - ./Nginx/nginx.key:/API/nginx.key
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate &&
             uvicorn API.asgi:application --port 8000 --host 0.0.0.0 --ssl-keyfile=./nginx.key --ssl-certfile=./nginx.crt"
    networks:
      - deploy
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - deploy

 

networks:

  deploy:
    driver: bridge

volumes:
  static_volumes:
  media_volumes:
