# Generated by Django 5.0.3 on 2024-03-19 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0002_profile_is_verified_alter_profile_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default=None, max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
                ('liked_users', models.ManyToManyField(blank=True, related_name='comment_liked_users', to='Profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default=None, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.ManyToManyField(blank=True, related_name='tweet_comments', to='SocialMedia.comment')),
                ('from_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
                ('liked_users', models.ManyToManyField(blank=True, related_name='tweet_liked_users', to='Profile.profile')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet', to='SocialMedia.tweet'),
        ),
    ]
