# Generated by Django 5.0.3 on 2024-03-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0006_remove_tweet_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='tweet_comments', to='SocialMedia.comment'),
        ),
    ]
