# Generated by Django 5.0.3 on 2024-03-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0008_remove_tweet_comments_alter_comment_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='image',
        ),
    ]
