# Generated by Django 5.0.3 on 2024-03-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0009_remove_tweet_image'),
    ]

    operations = [
    ]
