# Generated by Django 5.0.3 on 2024-03-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0010_tweet_image'),
    ]

    operations = [

    ]
