# Generated by Django 5.0.3 on 2024-03-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0009_remove_tweet_image'),
        ('SocialMedia', '0010_alter_comment_from_user_alter_tweet_from_user'),
    ]

    operations = [
    ]
