# Generated by Django 5.0.3 on 2024-03-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0011_merge_20240327_1221'),
    ]

    operations = [
    ]
