# Generated by Django 5.0.3 on 2024-03-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0013_remove_tweet_temp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='temp_id',
        ),
    ]
