# Generated by Django 5.0.3 on 2024-03-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0012_tweet_image'),
        ('SocialMedia', '0014_remove_tweet_temp_id'),
    ]

    operations = [
    ]
