# Generated by Django 5.0.3 on 2024-04-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0015_merge_0012_tweet_image_0014_remove_tweet_temp_id'),
    ]

    operations = [

    ]
