# Generated by Django 5.0.3 on 2024-04-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_alter_game_game_type_alter_game_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_type',
        ),
    ]
