# Generated by Django 5.0.3 on 2024-05-13 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField()),
                ('username', models.CharField()),
                ('expired_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
