# Generated by Django 5.0.3 on 2024-03-17 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0002_alter_tournament_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
