# Generated by Django 5.0.3 on 2024-04-16 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0021_merge_20240416_1353'),
        ('Tournament', '0008_round_tournament_rounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_matches', to='Profile.profile')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_matches', to='Profile.profile')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='Profile.profile')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='rounds', to='Tournament.match'),
        ),
    ]
