# Generated by Django 5.0.3 on 2024-04-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0021_merge_20240416_1353'),
        ('Tournament', '0009_match_round_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='participants',
            field=models.ManyToManyField(related_name='round_participants', to='Profile.profile'),
        ),
    ]
