# Generated by Django 5.0.3 on 2024-03-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='firs_user',
            new_name='first_user',
        ),
    ]
