# Generated by Django 5.0.3 on 2024-03-27 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_rename_firs_user_room_first_user'),
        ('Profile', '0013_profile_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Profile.profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='first_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_first', to='Profile.profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='second_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_second', to='Profile.profile'),
        ),
    ]
