# test.yml
name: Backend Test
on:
  push:
    branches: 
      - '**'
jobs:
  test-backend:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Django test
        run: |
          cd Backend
          pip install -r requirements.txt
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test
